SELECT COUNT(CHURN)
FROM DATASET
;
SELECT *
FROM DATASET
;
# CHECKING FOR DUPLICATE
SELECT *,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID, GENDER, PHONESERVICE, MULTIPLELINES, 
INTERNETSERVICE, CONTRACT, PAYMENTMETHOD, CHURN 
) AS ROW_NUM
FROM DATASET
;
WITH DUPLICATE_CTE AS
(SELECT *,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID, GENDER, PHONESERVICE, MULTIPLELINES, 
INTERNETSERVICE, CONTRACT, PAYMENTMETHOD, CHURN 
) AS ROW_NUM
FROM DATASET
)
SELECT *
FROM DUPLICATE_CTE 
WHERE ROW_NUM > 1
;
#DELETING THE DUPLICATE
CREATE TABLE `WORKSHEET` (
  `customerID` text,
  `gender` text,
  `SeniorCitizen` int DEFAULT NULL,
  `Partner` text,
  `Dependents` text,
  `tenure` int DEFAULT NULL,
  `PhoneService` text,
  `MultipleLines` text,
  `InternetService` text,
  `OnlineSecurity` text,
  `OnlineBackup` text,
  `DeviceProtection` text,
  `TechSupport` text,
  `StreamingTV` text,
  `StreamingMovies` text,
  `Contract` text,
  `PaperlessBilling` text,
  `PaymentMethod` text,
  `MonthlyCharges` double DEFAULT NULL,
  `TotalCharges` double DEFAULT NULL,
  `Churn` text,
  `ROW_NUM` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT *
FROM WORKSHEET
;
INSERT INTO WORKSHEET
SELECT *,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID, GENDER, PHONESERVICE, MULTIPLELINES, 
INTERNETSERVICE, CONTRACT, PAYMENTMETHOD, CHURN 
) AS ROW_NUM
FROM DATASET
;
DELETE 
FROM WORKSHEET
WHERE ROW_NUM > 1
;
SELECT *
FROM WORKSHEET
WHERE ROW_NUM > 1
;
SELECT *
FROM WORKSHEET
;
SELECT COUNT(CUSTOMERID)
FROM WORKSHEET
; 
#GENDER ANAYSIS
SELECT GENDER, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN = 'YES'
GROUP BY GENDER
ORDER BY 1
;
SELECT GENDER, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN = 'NO'
GROUP BY GENDER
ORDER BY 1
;
# PARTNER ALAYSIS
SELECT PARTNER, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN = 'YES'
GROUP BY PARTNER
ORDER BY 1
;
SELECT PARTNER, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN = 'NO'
GROUP BY PARTNER
ORDER BY 1
;
# TENURE ANALYSIS
SELECT 
CASE 
	WHEN TENURE >=0 AND TENURE <= 10 THEN '0-10'
    WHEN TENURE >=11 AND TENURE <= 20 THEN '11-20'
    WHEN TENURE >=21 AND TENURE <= 30 THEN '21-30'
    WHEN TENURE >=31 AND TENURE <= 40 THEN '31-40'
    WHEN TENURE >=41 AND TENURE <= 50 THEN '41-50'
    WHEN TENURE >=51 AND TENURE <= 60 THEN '51-60'
    WHEN TENURE >=61 AND TENURE <= 70 THEN '61-70'
    WHEN TENURE >=71 AND TENURE <= 80 THEN '71-80'
END AS TENURE_RANGE,
CHURN , COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN ='YES'
GROUP BY TENURE_RANGE
ORDER BY TENURE_RANGE
;SELECT 
CASE 
	WHEN TENURE >=0 AND TENURE <= 10 THEN '0-10'
    WHEN TENURE >=11 AND TENURE <= 20 THEN '11-20'
    WHEN TENURE >=21 AND TENURE <= 30 THEN '21-30'
    WHEN TENURE >=31 AND TENURE <= 40 THEN '31-40'
    WHEN TENURE >=41 AND TENURE <= 50 THEN '41-50'
    WHEN TENURE >=51 AND TENURE <= 60 THEN '51-60'
    WHEN TENURE >=61 AND TENURE <= 70 THEN '61-70'
    WHEN TENURE >=71 AND TENURE <= 80 THEN '71-80'
END AS TENURE_RANGE,
CHURN , COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE CHURN ='NO'
GROUP BY TENURE_RANGE
ORDER BY TENURE_RANGE
;
SELECT *
FROM WORKSHEET
;
# PHONE SERVICE
SELECT PHONESERVICE, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY PHONESERVICE
ORDER BY 1
;
SELECT PHONESERVICE, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY PHONESERVICE
ORDER BY 1
;
#  MULTIPLE_LINES ANALYSIS
SELECT MULTIPLELINES, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  MULTIPLELINES
ORDER BY 1
;
SELECT MULTIPLELINES, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  MULTIPLELINES
ORDER BY 1
;
# INTERNET_SERVICE ANALYSIS
SELECT INTERNETSERVICE, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  INTERNETSERVICE
ORDER BY 1
;
SELECT INTERNETSERVICE, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  INTERNETSERVICE
ORDER BY 1
;
# ONLINE_SECURITY ANALYSIS
SELECT ONLINESECURITY, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  ONLINESECURITY
ORDER BY 1
;
SELECT ONLINESECURITY, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  ONLINESECURITY
ORDER BY 1
;
# ONLINE_BACKUP ANALYSIS
SELECT ONLINEBACKUP, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  ONLINEBACKUP
ORDER BY 1
;
SELECT ONLINEBACKUP, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  ONLINEBACKUP
ORDER BY 1
;
# DEVIC_ PROTECTION ANALYSIS
SELECT DEVICEPROTECTION, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  DEVICEPROTECTION
ORDER BY 1
;
SELECT DEVICEPROTECTION, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  DEVICEPROTECTION
ORDER BY 1
;
# TECH_SUPPORT ANALYSIS
SELECT TECHSUPPORT, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  TECHSUPPORT
ORDER BY 1
;
SELECT TECHSUPPORT, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  TECHSUPPORT
ORDER BY 1
;
# CONTRACT ANALYSIS
SELECT CONTRACT, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  CONTRACT
ORDER BY 1
;
SELECT CONTRACT, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  CONTRACT
ORDER BY 1
;
# PAYMENT_METHOD ANALYSIS
SELECT PAYMENTMETHOD, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='YES'
GROUP BY  PAYMENTMETHOD
ORDER BY 1
;
SELECT PAYMENTMETHOD, CHURN, COUNT(CUSTOMERID)
FROM WORKSHEET
WHERE  CHURN ='NO'
GROUP BY  PAYMENTMETHOD
ORDER BY 1
;

